-- PharmFlow Receiving History — lightweight workspace/discrepancy/NEW-item history.
-- Additive and backward compatible. Existing Archive remains untouched during rollout.

create table if not exists public.pharmflow_receiving_workspace_history_v1 (
    id uuid primary key default gen_random_uuid(),
    pharmacy_id uuid not null,
    completion_key text not null,
    completed_at timestamptz not null default now(),
    completed_by uuid not null,
    orders_count integer not null default 0 check (orders_count >= 0),
    discrepancy_count integer not null default 0 check (discrepancy_count >= 0),
    new_item_count integer not null default 0 check (new_item_count >= 0),
    order_numbers text[] not null default '{}'::text[],
    created_at timestamptz not null default now(),
    unique (pharmacy_id, completion_key)
);

create index if not exists idx_pf_receiving_workspace_history_date
    on public.pharmflow_receiving_workspace_history_v1(pharmacy_id, completed_at desc);

create table if not exists public.pharmflow_receiving_history_items_v1 (
    id bigint generated by default as identity primary key,
    pharmacy_id uuid not null,
    workspace_history_id uuid not null references public.pharmflow_receiving_workspace_history_v1(id) on delete cascade,
    event_type text not null check (event_type in ('DISCREPANCY','NEW_ITEM')),
    order_number text not null,
    order_name text not null default '',
    order_date date,
    item_code text not null,
    item_name text not null default '',
    ordered_qty numeric not null default 0,
    received_qty numeric,
    difference numeric,
    issue_type text not null default '',
    created_at timestamptz not null default now()
);

create index if not exists idx_pf_receiving_history_items_workspace
    on public.pharmflow_receiving_history_items_v1(pharmacy_id, workspace_history_id, event_type, order_number);
create index if not exists idx_pf_receiving_history_items_new
    on public.pharmflow_receiving_history_items_v1(pharmacy_id, event_type, created_at desc);

alter table public.pharmflow_receiving_workspace_history_v1 enable row level security;
alter table public.pharmflow_receiving_history_items_v1 enable row level security;

drop policy if exists pf_receiving_workspace_history_select on public.pharmflow_receiving_workspace_history_v1;
create policy pf_receiving_workspace_history_select
on public.pharmflow_receiving_workspace_history_v1
for select to authenticated
using (public.is_pharmacy_member(pharmacy_id));

drop policy if exists pf_receiving_history_items_select on public.pharmflow_receiving_history_items_v1;
create policy pf_receiving_history_items_select
on public.pharmflow_receiving_history_items_v1
for select to authenticated
using (public.is_pharmacy_member(pharmacy_id));

revoke all on table public.pharmflow_receiving_workspace_history_v1 from public,anon;
revoke all on table public.pharmflow_receiving_history_items_v1 from public,anon;
grant select on table public.pharmflow_receiving_workspace_history_v1 to authenticated;
grant select on table public.pharmflow_receiving_history_items_v1 to authenticated;

create or replace function public.finalize_pharmflow_receiving_workspace_v1(
    p_pharmacy_id uuid,
    p_completion_key text,
    p_order_numbers text[],
    p_discrepancies jsonb default '[]'::jsonb,
    p_new_items jsonb default '[]'::jsonb
)
returns table(workspace_history_id uuid, completed_at timestamptz, orders_count integer, discrepancy_count integer, new_item_count integer)
language plpgsql
security definer
set search_path to 'public','pg_temp'
as $function$
declare
    v_id uuid;
    v_completed_at timestamptz;
    v_orders text[];
    v_order text;
    v_status text;
    v_disc_count integer;
    v_new_count integer;
begin
    if auth.uid() is null or not public.is_pharmacy_admin(p_pharmacy_id) then
        raise exception 'Pharmacy ADMIN access required';
    end if;
    if nullif(trim(coalesce(p_completion_key,'')),'') is null then
        raise exception 'Completion key required';
    end if;
    select coalesce(array_agg(distinct upper(regexp_replace(trim(x),'\s','','g')) order by upper(regexp_replace(trim(x),'\s','','g'))),'{}'::text[])
      into v_orders
      from unnest(coalesce(p_order_numbers,'{}'::text[])) x
     where nullif(trim(x),'') is not null;
    if coalesce(array_length(v_orders,1),0)=0 then
        raise exception 'At least one Order Number is required';
    end if;
    if jsonb_typeof(coalesce(p_discrepancies,'[]'::jsonb)) <> 'array'
       or jsonb_typeof(coalesce(p_new_items,'[]'::jsonb)) <> 'array' then
        raise exception 'History items must be JSON arrays';
    end if;

    select h.id,h.completed_at into v_id,v_completed_at
      from public.pharmflow_receiving_workspace_history_v1 h
     where h.pharmacy_id=p_pharmacy_id and h.completion_key=trim(p_completion_key);
    if found then
        return query
        select h.id,h.completed_at,h.orders_count,h.discrepancy_count,h.new_item_count
          from public.pharmflow_receiving_workspace_history_v1 h
         where h.id=v_id;
        return;
    end if;

    foreach v_order in array v_orders loop
        select o.status into v_status
          from public.pharmflow_orders o
         where o.pharmacy_id=p_pharmacy_id
           and upper(regexp_replace(o.order_number,'\s','','g'))=v_order
         for update;
        if v_status is null then raise exception 'Order % is not registered',v_order; end if;
        if v_status='received' then raise exception 'Order % has already been received/finalized',v_order; end if;
    end loop;

    v_disc_count=jsonb_array_length(coalesce(p_discrepancies,'[]'::jsonb));
    v_new_count=jsonb_array_length(coalesce(p_new_items,'[]'::jsonb));

    insert into public.pharmflow_receiving_workspace_history_v1(
        pharmacy_id,completion_key,completed_by,orders_count,discrepancy_count,new_item_count,order_numbers
    ) values(
        p_pharmacy_id,trim(p_completion_key),auth.uid(),array_length(v_orders,1),v_disc_count,v_new_count,v_orders
    )
    returning id,completed_at into v_id,v_completed_at;

    insert into public.pharmflow_receiving_history_items_v1(
        pharmacy_id,workspace_history_id,event_type,order_number,order_name,order_date,
        item_code,item_name,ordered_qty,received_qty,difference,issue_type
    )
    select p_pharmacy_id,v_id,'DISCREPANCY',
           upper(regexp_replace(trim(coalesce(x->>'order_number','')),'\s','','g')),
           coalesce(x->>'order_name',''),nullif(x->>'order_date','')::date,
           trim(coalesce(x->>'item_code','')),coalesce(x->>'item_name',''),
           coalesce(nullif(x->>'ordered_qty','')::numeric,0),
           nullif(x->>'received_qty','')::numeric,
           nullif(x->>'difference','')::numeric,
           upper(trim(coalesce(x->>'issue_type','')))
      from jsonb_array_elements(coalesce(p_discrepancies,'[]'::jsonb)) x
     where upper(regexp_replace(trim(coalesce(x->>'order_number','')),'\s','','g'))=any(v_orders)
       and nullif(trim(coalesce(x->>'item_code','')),'') is not null;

    insert into public.pharmflow_receiving_history_items_v1(
        pharmacy_id,workspace_history_id,event_type,order_number,order_name,order_date,
        item_code,item_name,ordered_qty,received_qty,difference,issue_type
    )
    select p_pharmacy_id,v_id,'NEW_ITEM',
           upper(regexp_replace(trim(coalesce(x->>'order_number','')),'\s','','g')),
           coalesce(x->>'order_name',''),nullif(x->>'order_date','')::date,
           trim(coalesce(x->>'item_code','')),coalesce(x->>'item_name',''),
           coalesce(nullif(x->>'ordered_qty','')::numeric,0),null,null,'NEW'
      from jsonb_array_elements(coalesce(p_new_items,'[]'::jsonb)) x
     where upper(regexp_replace(trim(coalesce(x->>'order_number','')),'\s','','g'))=any(v_orders)
       and nullif(trim(coalesce(x->>'item_code','')),'') is not null;

    update public.pharmflow_orders
       set status='received',received_at=v_completed_at,received_by=auth.uid()
     where pharmacy_id=p_pharmacy_id
       and upper(regexp_replace(order_number,'\s','','g'))=any(v_orders);

    return query select v_id,v_completed_at,array_length(v_orders,1),v_disc_count,v_new_count;
end;
$function$;

revoke all on function public.finalize_pharmflow_receiving_workspace_v1(uuid,text,text[],jsonb,jsonb) from public,anon;
grant execute on function public.finalize_pharmflow_receiving_workspace_v1(uuid,text,text[],jsonb,jsonb) to authenticated;

create or replace function public.list_pharmflow_receiving_workspace_history_v1(
    p_pharmacy_id uuid,p_from date,p_to date
)
returns table(workspace_history_id uuid,completed_at timestamptz,orders_count integer,discrepancy_count integer,new_item_count integer,order_numbers text[])
language sql stable security definer set search_path=public,pg_temp
as $function$
    select h.id,h.completed_at,h.orders_count,h.discrepancy_count,h.new_item_count,h.order_numbers
      from public.pharmflow_receiving_workspace_history_v1 h
     where h.pharmacy_id=p_pharmacy_id
       and auth.uid() is not null and public.is_pharmacy_member(p_pharmacy_id)
       and h.completed_at >= p_from::timestamptz
       and h.completed_at < (p_to + 1)::timestamptz
     order by h.completed_at desc;
$function$;
revoke all on function public.list_pharmflow_receiving_workspace_history_v1(uuid,date,date) from public,anon;
grant execute on function public.list_pharmflow_receiving_workspace_history_v1(uuid,date,date) to authenticated;

create or replace function public.get_pharmflow_receiving_workspace_history_v1(
    p_pharmacy_id uuid,p_workspace_history_id uuid
)
returns table(event_type text,order_number text,order_name text,order_date date,item_code text,item_name text,ordered_qty numeric,received_qty numeric,difference numeric,issue_type text)
language sql stable security definer set search_path=public,pg_temp
as $function$
    select i.event_type,i.order_number,i.order_name,i.order_date,i.item_code,i.item_name,
           i.ordered_qty,i.received_qty,i.difference,i.issue_type
      from public.pharmflow_receiving_history_items_v1 i
     where i.pharmacy_id=p_pharmacy_id
       and i.workspace_history_id=p_workspace_history_id
       and auth.uid() is not null and public.is_pharmacy_member(p_pharmacy_id)
     order by i.order_number,
              case i.event_type when 'DISCREPANCY' then 1 else 2 end,
              i.item_name,i.item_code;
$function$;
revoke all on function public.get_pharmflow_receiving_workspace_history_v1(uuid,uuid) from public,anon;
grant execute on function public.get_pharmflow_receiving_workspace_history_v1(uuid,uuid) to authenticated;

create or replace function public.list_pharmflow_new_item_history_v1(
    p_pharmacy_id uuid,p_from date,p_to date
)
returns table(workspace_history_id uuid,completed_at timestamptz,order_number text,order_name text,order_date date,item_code text,item_name text,ordered_qty numeric)
language sql stable security definer set search_path=public,pg_temp
as $function$
    select h.id,h.completed_at,i.order_number,i.order_name,i.order_date,i.item_code,i.item_name,i.ordered_qty
      from public.pharmflow_receiving_workspace_history_v1 h
      join public.pharmflow_receiving_history_items_v1 i
        on i.workspace_history_id=h.id and i.pharmacy_id=h.pharmacy_id
     where h.pharmacy_id=p_pharmacy_id and i.event_type='NEW_ITEM'
       and auth.uid() is not null and public.is_pharmacy_member(p_pharmacy_id)
       and h.completed_at >= p_from::timestamptz
       and h.completed_at < (p_to + 1)::timestamptz
     order by h.completed_at desc,i.order_number,i.item_name,i.item_code;
$function$;
revoke all on function public.list_pharmflow_new_item_history_v1(uuid,date,date) from public,anon;
grant execute on function public.list_pharmflow_new_item_history_v1(uuid,date,date) to authenticated;
