const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {harness}=require('./expiry-capture-review.test.cjs');
async function scan(){const h=harness(true);h.c.engine.selectedWorkerId='worker1';h.c.confirm=()=>true;await h.c.resolveExpiryScannedValue('(01)04065272072977(17)270831');return h;}
test('Two operators share receipt references and authoritative immutable attribution, newest first',async()=>{
 const h=await scan(),rpc=h.c.authRpc;
 h.c.authRpc=async(n,p)=>{const r=await rpc(n,p);if(n==='save_pharmflow_expiry_capture_v3'){const row=h.receipts.get(p.p_operation_id);row.operator_name=p.p_capture.worker_id==='worker1'?'Operator One':'Operator Two';row.captured_at=p.p_capture.worker_id==='worker1'?'2026-10-09T00:00:00Z':'2026-10-09T00:01:00Z';}return r;};
 await h.c.saveExpiryCapture();h.c.selectExpiryWorker('worker2');await h.c.resolveExpiryScannedValue('U0030');h.c.setExpiryControlValue(h.e('expiryMonth'),'10');h.c.setExpiryControlValue(h.e('expiryYear'),'2027');await h.c.saveExpiryCapture();
 let rows=await h.c.loadExpirySessionReceipts();assert.equal(rows.length,2);assert.equal(rows[0].operator_name,'Operator Two');assert.equal(rows[1].operator_name,'Operator One');
 h.c.selectExpiryWorker('worker1');rows=await h.c.loadExpirySessionReceipts();assert.equal(rows[0].operator_name,'Operator Two');assert.equal(rows[1].worker_id,'worker1');
 await h.c.openExpiryRecentScans();const markup=h.c.document.body.children.at(-1).innerHTML;assert.match(markup,/<details/);assert.match(markup,/<summary>/);assert.match(markup,/Operator One/);assert.match(markup,/Operator Two/);assert.match(markup,/Identifier:/);assert.doesNotMatch(markup,/data-delete|data-edit/);
 h.c.clearExpirySessionHistory();assert.equal((await h.c.loadExpirySessionReceipts()).length,0);assert.equal(h.receipts.size,2);
});
test('Single success notice follows receipt and does not populate persistent saved details',async()=>{const h=await scan();await h.c.saveExpiryCapture();assert.equal(h.e('expiryScanStatus').textContent,'Saved · Ready to Scan');assert.equal(h.e('expiryLastSaved').innerHTML,'');assert.equal(h.c.engine.currentItem,null);});
test('Clear confirms genuine unsaved data and removes only local draft, never saved records',async()=>{const h=await scan();await h.c.persistExpiryDraft();h.c.confirm=()=>false;assert.equal(await h.c.clearExpiryHandheldCapture(),false);assert.ok(h.c.engine.currentItem);h.c.confirm=()=>true;h.e('expiryBarcodeInput').value='pending';assert.equal(await h.c.clearExpiryHandheldCapture(),true);assert.equal(h.drafts.size,0);assert.equal(h.e('expiryBarcodeInput').value,'');assert.equal(h.c.engine.currentItem,null);assert.equal(h.e('expiryMonth').dataset.value,'');assert.equal(h.e('expiryYear').dataset.value,'');assert.equal(h.calls.length,0);});
test('Clear handles pending recovery and fails closed if stored draft changed',async()=>{const h=await scan();await h.c.persistExpiryDraft();h.c.resetExpiryCaptureForm();await h.c.prepareExpiryDraftRecovery();assert.equal(await h.c.clearExpiryHandheldCapture(),true);assert.equal(h.drafts.size,0);const j=await scan();await j.c.persistExpiryDraft();j.drafts.get('user1/isolated-test').status='UNCERTAIN';assert.equal(await j.c.clearExpiryHandheldCapture(),false);assert.ok(j.c.engine.currentItem);});
test('Back preserves an unsaved draft for explicit recovery; cancelled Back keeps form',async()=>{const h=await scan();let back=0;h.c.setZebraHomeMode=()=>back++;h.c.confirm=()=>false;assert.equal(await h.c.leaveExpiryHandheld(),false);assert.equal(back,0);h.c.confirm=()=>true;assert.equal(await h.c.leaveExpiryHandheld(),true);assert.equal(back,1);assert.equal(h.c.engine.currentItem,null);assert.equal(h.drafts.size,1);await h.c.prepareExpiryDraftRecovery();assert.ok(h.c.engine.pendingDraft);assert.equal(h.c.engine.currentItem,null);});
test('Back on clean form uses only existing workspace selector',async()=>{const h=harness(true);let back=0;h.c.setZebraHomeMode=()=>back++;assert.equal(await h.c.leaveExpiryHandheld(),true);assert.equal(back,1);assert.equal(h.calls.length,0);});
test('Clear and Back refuse resolving, in-flight, uncertain and submitted captures',async()=>{for(const field of ['busy','resolving','saveUncertain','payload']){const h=await scan();let back=0;h.c.setZebraHomeMode=()=>back++;if(field==='payload')h.c.engine.operation={id:'op',payload:{}};else h.c.engine[field]=true;assert.equal(await h.c.clearExpiryHandheldCapture(),false);assert.equal(await h.c.leaveExpiryHandheld(),false);assert.ok(h.c.engine.currentItem);assert.equal(back,0);}});
test('Back storage failure retains form and prevents navigation',async()=>{const h=await scan();let back=0;h.c.setZebraHomeMode=()=>back++;h.c.ExpiryDraftStore.put=async()=>{throw Error('offline')};assert.equal(await h.c.leaveExpiryHandheld(),false);assert.ok(h.c.engine.currentItem);assert.equal(back,0);});
test('Canonical styling separates option indicator and text, bold values; mandatory blank expiry unchanged',()=>{const css=fs.readFileSync('css/dashboard.css','utf8'),html=fs.readFileSync('index.html','utf8');assert.match(css,/pfSelectOption\{display:flex;align-items:center;justify-content:space-between;gap:12px/);assert.match(css,/pfSelectTrigger\{[^}]*font-weight:750/);for(const id of ['expiryMonth','expiryYear'])assert.match(html,new RegExp('id="'+id+'"[^>]*data-value=""'));assert.equal(html.split('id="btnExpiryBackToModes"').length-1,1);});
test('Pending uncertain recovery blocks Back and Clear without touching the draft',async()=>{const h=await scan();await h.c.persistExpiryDraft('UNCERTAIN');h.c.resetExpiryCaptureForm();await h.c.prepareExpiryDraftRecovery();assert.equal(await h.c.leaveExpiryHandheld(),false);assert.equal(await h.c.clearExpiryHandheldCapture(),false);assert.equal(h.drafts.size,1);});
test('Existing Operator-scoped session IDs are adopted without copying capture facts',()=>{const h=harness(true);h.c.engine.selectedWorkerId='worker1';h.session.set('pharmflow_expiry_recent_user1/isolated-test/synthetic-device/worker1',JSON.stringify({id:'existing-session',scope:'user1/isolated-test',deviceId:'synthetic-device',workerId:'worker1',operations:['original-operation']}));const {session}=h.c.expiryHandheldSession();assert.equal(session.id,'existing-session');assert.equal(session.operators['original-operation'],'worker1');assert.equal(session.item_name,undefined);});
