"use strict";
const fs=require("fs"),assert=require("assert");
const html=fs.readFileSync("index.html","utf8");
const ui=fs.readFileSync("ui.js","utf8");
const reports=fs.readFileSync("js/reports.js","utf8");
const receiving=fs.readFileSync("js/receiving.js","utf8");\nconst cloud=fs.readFileSync("js/cloud-workspace.js","utf8");\nconst app=fs.readFileSync("js/app.js","utf8");
assert(html.includes("Extra Items"));
assert(!html.includes("Manual Extras"));
assert(reports.includes("Extra Items are reconstructed from durable Receiving transactions"));
assert(reports.includes('"Issue Type":"Extra Item"'));
assert(receiving.includes("gtinItemMetrics"));
assert(receiving.includes("Already Received"));
assert(receiving.includes("After this scan:"));
assert(receiving.includes("data-change-item"));
assert(receiving.includes("search.hidden=true;results.hidden=true"));
assert(ui.includes('"Extra Items"'));
const bootstrapStart=cloud.indexOf("async function bootstrapActiveOrdersOnEmptyDevice");
const bootstrapEnd=cloud.indexOf("window.bootstrapActiveOrdersOnEmptyDevice",bootstrapStart);
assert(bootstrapStart>=0 && bootstrapEnd>bootstrapStart);
const bootstrapBody=cloud.slice(bootstrapStart,bootstrapEnd);
assert(!bootstrapBody.includes("await pullCloudWorkspaceTransactions()"),"manifest bootstrap must not pre-hydrate ledger before legacy workspace restore");
const restoreStart=cloud.indexOf("async function restoreCloudWorkspaceOnLogin");
const restoreEnd=cloud.indexOf("async function reconcileCloudWorkspaceAuthority",restoreStart);
const restoreBody=cloud.slice(restoreStart,restoreEnd);
assert(restoreBody.includes("await pullActiveOrderManifest();"));
assert(restoreBody.includes("await pullCloudWorkspaceTransactions();"));
assert(restoreBody.indexOf("await pullActiveOrderManifest();")<restoreBody.lastIndexOf("await pullCloudWorkspaceTransactions();"),"authoritative ledger pull must follow structural hydration");
assert(app.includes('manual:row.issueKey==="manual"'),"dashboard must preserve durable Extra Item classification");
console.log("Extra Items and selected-item UX guards: PASS");
