"use strict";
const fs=require("fs");
const assert=require("assert");
const html=fs.readFileSync("index.html","utf8");
const auth=fs.readFileSync("js/auth.js","utf8");
const css=fs.readFileSync("css/style.css","utf8");
const sql=fs.readFileSync("PHASE2C1170_SETTINGS_PHARMACY_IDENTITY_V2.sql","utf8");

assert(!html.includes('>Activate Pharmacy Admin</button>'),"Public Activate Admin action must be removed");
assert(!html.includes('id="publicSignupName"'),"Public signup must not request User Name");
assert(!html.includes('id="publicPharmacyName"'),"Public signup must not request Pharmacy Name");
assert(html.includes('id="publicPharmacyCode"'),"Public signup must request a proposed Pharmacy Code");
assert(html.includes('id="publicSignupPasswordConfirm"'),"Public signup must confirm password");
assert(auth.includes('submit_pharmacy_registration_v2'),"Registration must use V2 request contract");
assert(auth.includes('owner_review_pharmacy_registration_v2'),"Owner approval must assign official identity");
assert(auth.includes('owner_update_pharmacy_identity_v1'),"Owner must be able to correct pharmacy identity safely");
assert(auth.includes('pharmflow-password-admin'),"Password reset must use trusted server function");
assert(auth.includes('No recovery email will be sent'),"Forgot Password must not send recovery email");
assert(auth.includes('pharmflow_must_change_password'),"Temporary password must force replacement");
assert(html.includes('data-owner-view="total"'),"Total KPI must open a management view");
assert(html.includes('data-owner-view="active"'),"Active KPI must open a management view");
assert(html.includes('data-owner-view="pending"'),"Pending KPI must open a management view");
assert(html.includes('data-owner-view="admins"'),"Admins KPI must open a management view");
assert(html.includes('id="ownerManagementPanel"'),"Owner management panel must exist");
assert(auth.includes('function openOwnerManagementPanel(view)'),"KPI management navigation must be implemented");
assert(auth.includes('function renderOwnerManagementPanel()'),"Owner management panel renderer must exist");
assert(html.includes('class="modalOverlay ownerManagementOverlay"'),"KPI management must use the established PharmFlow modal pattern");
assert(css.includes('.ownerManagementOverlay .ownerManagementPanel{'),"Owner management modal must use dedicated PharmFlow styling");
assert(css.includes('.registrationRequestsList[hidden]'),"Hidden pending and pharmacy views must not leak into each other");
assert(css.includes('max-height:65vh'),"Management lists must use internal modal scroll");
assert(html.includes('id="btnEditSettingsIdentity"'),"System Owner account card must expose identity Edit");
assert(auth.includes('setSettingsIdentityEditMode'),"Account edit must use the same card edit mode");
assert(auth.includes('owner_update_pharmacy_identity_v1'),"Account edit must reuse canonical identity RPC");
assert(!html.includes('id="accountDisplayNameInput"'),"User Name must remain absent from current Settings UX");
assert(sql.includes('pharmflow_pharmacy_identity_audit_v1'),"Identity changes must be audited");
assert(sql.includes('p.id<>p_pharmacy_id'),"Official pharmacy code collision must be blocked");
assert(!sql.includes('delete from public.pharmacies'),"Identity correction must never delete pharmacy data");
console.log("PASS settings account/access regression");
