-- PharmFlow Phase 2C.6.1 — Safe GTIN Learning & Owner-only Global Master
-- Idempotent. Learned mappings are pharmacy-scoped and never modify the System Global Master.

create table if not exists public.pharmacy_learned_gtin (
  id bigint generated by default as identity primary key,
  pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
  gtin text not null,
  item_code text not null,
  item_name text not null,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  use_count bigint not null default 1,
  unique(pharmacy_id,gtin)
);
create index if not exists idx_pharmacy_learned_gtin_code on public.pharmacy_learned_gtin(pharmacy_id,item_code);
alter table public.pharmacy_learned_gtin enable row level security;

create or replace function public.pharmflow_is_member(p_pharmacy_id uuid)
returns boolean language sql stable security definer set search_path=public,pg_temp as $$
 select exists(select 1 from public.system_owners so where so.user_id=auth.uid())
 or exists(select 1 from public.pharmacy_members pm where pm.pharmacy_id=p_pharmacy_id and pm.user_id=auth.uid());
$$;

create or replace function public.resolve_pharmacy_learned_gtin(p_pharmacy_id uuid,p_gtin text)
returns table(item_code text,item_name text)
language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if auth.uid() is null or not public.pharmflow_is_member(p_pharmacy_id) then raise exception 'Pharmacy access required'; end if;
 return query select l.item_code,l.item_name from public.pharmacy_learned_gtin l
  where l.pharmacy_id=p_pharmacy_id and regexp_replace(l.gtin,'[^0-9]','','g')=regexp_replace(coalesce(p_gtin,''),'[^0-9]','','g') limit 1;
end; $$;

create or replace function public.learn_pharmacy_gtin(p_pharmacy_id uuid,p_gtin text,p_item_code text,p_item_name text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_gtin text:=regexp_replace(coalesce(p_gtin,''),'[^0-9]','','g'); v_code text:=trim(coalesce(p_item_code,'')); v_name text:=trim(coalesce(p_item_name,'')); v_existing text;
begin
 if auth.uid() is null or not public.pharmflow_is_member(p_pharmacy_id) then raise exception 'Pharmacy access required'; end if;
 if length(v_gtin)<8 or v_code='' or v_name='' then raise exception 'Valid GTIN, Item Code and Item Name are required'; end if;
 select item_code into v_existing from public.pharmacy_learned_gtin where pharmacy_id=p_pharmacy_id and gtin=v_gtin limit 1;
 if v_existing is not null and v_existing<>v_code then raise exception 'GTIN conflict: this pharmacy already mapped this GTIN to Item Code %',v_existing; end if;
 insert into public.pharmacy_learned_gtin(pharmacy_id,gtin,item_code,item_name,created_by)
 values(p_pharmacy_id,v_gtin,v_code,v_name,auth.uid())
 on conflict(pharmacy_id,gtin) do update set item_name=excluded.item_name,updated_at=now(),use_count=public.pharmacy_learned_gtin.use_count+1;
 return jsonb_build_object('success',true,'scope','pharmacy','gtin',v_gtin,'item_code',v_code);
end; $$;

revoke all on function public.resolve_pharmacy_learned_gtin(uuid,text) from public,anon;
revoke all on function public.learn_pharmacy_gtin(uuid,text,text,text) from public,anon;
grant execute on function public.resolve_pharmacy_learned_gtin(uuid,text) to authenticated;
grant execute on function public.learn_pharmacy_gtin(uuid,text,text,text) to authenticated;

-- Database-level protection: direct/bulk changes to Global Master are System Owner only.
create or replace function public.guard_global_master_owner_only()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if auth.uid() is null or not exists(select 1 from public.system_owners so where so.user_id=auth.uid()) then
   raise exception 'System Owner access is required to update Global Master GTIN';
 end if;
 return coalesce(new,old);
end; $$;

do $$
declare t text;
begin
 foreach t in array array['pharmacy_master_gtin_v2','pharmacy_master_gtin_import_rows_v2','pharmacy_master_gtin_imports_v2','pharmacy_master_gtin_meta_v2'] loop
  if to_regclass('public.'||t) is not null then
   execute format('drop trigger if exists trg_owner_only_global_master on public.%I',t);
   execute format('create trigger trg_owner_only_global_master before insert or update or delete on public.%I for each row execute function public.guard_global_master_owner_only()',t);
  end if;
 end loop;
end $$;
